#!/usr/bin/env python3
import turtle
tim=turtle.Turtle()
tim.shape('turtle')
tim.color('red')
tim.pensize(5)
tim.speed(3)
tim.shape('arrow')
tim.right(90)
for i in range(2):
    tim.left(72)
    tim.forward(100)
tim.color('gold')
for i in range(3):
    tim.left(72)
    tim.forward(100)
tim.penup()
tim.forward(150)
tim.pendown()
tim.color('green')
tim.forward(80)
dave=turtle.Turtle()
dave.pensize(3)
dave.color('blue')
dave.shape('turtle')
dave.penup()
dave.setx(-50)
dave.sety(-60)
dave.speed(10)
dave.pendown()
dave.backward(140)
turtle.done()
